version: '3'

services:
  continuous_double_auction:
    build: .
    ports:
      - '9001:9001'

  frequent_batch_auction:
    build: .
    ports:
      - '9002:9001'
    environment:
      - MECHANISM=fba
      - INTERVAL=1
